apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopszon-client
  namespace: devopszon
  annotations:
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  ingressClassName: nginx
  rules:
    - host: console.devopszon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devopszon-client
                port:
                  number: 80
    - host: deneme.devopszon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devopszon-client
                port:
                  number: 80
  tls:
    - hosts:
      - console.devopszon.com
      secretName: devopszon-client-ingress-secret
    - hosts:
      - deneme.devopszon.com
      secretName: devopszon-client-ingress-secret
