apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopszon-client
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devopszon
  source:
    repoURL: https://github.com/devopszon/devopszon-dev-devopszon-client-3a1d7056-aa19-eb02-a21c-b6c56c773b11.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: devopszon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true