apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopszon
  name: devopszon-client
  labels:
    app: devopszon-client
    project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: devopszon-client
      project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
  template:
    metadata:
      labels:
        app: devopszon-client
        service: devopszon-client
        project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-limits-cpu: '500m'
        vault.hashicorp.com/agent-limits-mem: '128Mi'
        vault.hashicorp.com/agent-requests-cpu: '250m'
        vault.hashicorp.com/agent-requests-mem: '64Mi'
        vault.hashicorp.com/agent-configmap: 'devopszon-client-vault-config'
    spec:
      serviceAccountName: devopszon-client
      imagePullSecrets:
      - name: devopszon-client-registry-secret
      
      
      containers:
        - name: devopszon-client
          image: docker.io/cahityusuf/devopszon-client:v1.0.99
          command: ["/bin/sh", "-c"]
          args:
            - |
              set +x
                if [ -f /vault/secrets/env ]; then
                    grep -v '^#' /vault/secrets/env | sed 's/^/export /' > /tmp/formatted_env
                    . /tmp/formatted_env >/dev/null 2>&1
                fi
                exec /docker-entrypoint.sh nginx -g "daemon off;"
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          
          
             