apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devopszon-client
    project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
  name: devopszon-client
  namespace: devopszon
spec:
  replicas: 1
  selector:
    matchLabels:
      service: devopszon-client
      project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-configmap: devopszon-client-vault-config
        vault.hashicorp.com/agent-limits-cpu: 500m
        vault.hashicorp.com/agent-limits-mem: 128Mi
        vault.hashicorp.com/agent-requests-cpu: 250m
        vault.hashicorp.com/agent-requests-mem: 64Mi
      labels:
        app: devopszon-client
        service: devopszon-client
        project-id: devopszon-client-3a1d6f64-5897-e03b-c4de-b5e698301e9a
    spec:
      containers:
      - args:
        - |-
          set +x
          if [ -f /vault/secrets/env ]; then
              grep -v '^#' /vault/secrets/env | sed 's/^/export /' > /tmp/formatted_env
              . /tmp/formatted_env >/dev/null 2>&1
          fi
          exec /docker-entrypoint.sh nginx -g "daemon off;"
        command:
        - /bin/sh
        - -c
        image: docker.io/cahityusuf/devopszon-client:v1.2.2
        name: devopszon-client
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 512Mi
            cpu: 500m
        workingDir: /app
      imagePullSecrets:
      - name: devopszon-client-registry-secret
      serviceAccountName: devopszon-client
      volumes: []