apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: devopszon-client-ingress
  namespace: devopszon
spec:
  ingressClassName: nginx
  rules:
  - host: console.devopszon.com
    http:
      paths:
      - backend:
          service:
            name: devopszon-client
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: deneme.devopszon.com
    http:
      paths:
      - backend:
          service:
            name: devopszon-client
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - console.devopszon.com
    secretName: console-devopszon-com-tls-secret
  - hosts:
    - deneme.devopszon.com
    secretName: deneme-devopszon-com-tls-secret