apiVersion: v1
kind: Service
metadata:
  labels:
    app: devopszon-client
    service: devopszon-client
  name: devopszon-client
  namespace: devopszon
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: devopszon-client
  type: ClusterIP