apiVersion: v1
kind: Service
metadata:
  name: devopszon-client
  namespace: devopszon
  labels:
    app: devopszon-client
    service: devopszon-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    service: devopszon-client
  